### PR TITLE
Rebase on .NET Standard 2.0

### PR DESCRIPTION
**Pull request by danielgindi**
I know that iText 5 is EOL, but for people who are trying to migrate to newer technologies, it becomes very complex do it all at once.
Allowing itextsharp to compile for .NET Standard removes this obstacle from the way.

### CODE REVIEW

**Comment by andreycha** [comment]
Hi @danielgindi . I've tried your packages from Nuget.org (https://www.nuget.org/packages/Portable.itextsharp and https://www.nuget.org/packages/Portable.itextsharp.xmlworker) and found out that converting HTML to PDF using `XmlWorkerHelper` does not work. Calling `Document.Close()` throws `"System.IOException: The document has no pages."` (using [this sample from SO](https://stackoverflow.com/a/25164258/1985167)). Have you tried it out and could you maybe advise anything?

**Comment by danielgindi** [comment]
> Hi @danielgindi . I've tried your packages from Nuget.org (https://www.nuget.org/packages/Portable.itextsharp and https://www.nuget.org/packages/Portable.itextsharp.xmlworker) and found out that converting HTML to PDF using `XmlWorkerHelper` does not work. Calling `Document.Close()` throws `"System.IOException: The document has no pages."` (using [this sample from SO](https://stackoverflow.com/a/25164258/1985167)). Have you tried it out and could you maybe advise anything?

I did not try the helper specifically, but found out that when using in .NET Core env, I needed to register the used codepages with the system encoding, as it only had just about utf8 out of the box, so iText could not load fonts. It might be related.

**Comment by andreycha** [comment]
Could you please share relevant code sample? If you meant using `System.Text.Encoding.CodePages` package and adding `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);` then unfortunately it doesn't help...

**Comment by danielgindi** [comment]
> Could you please share relevant code sample? If you meant using `System.Text.Encoding.CodePages` package and adding `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);` then unfortunately it doesn't help...

Exactly what I meant...
Maybe try to debug it? You can download the fork and compile locally easily.
Then you could perhaps find what's the source of the issue. I can say  that manual pdf generation works perfectly.

**Comment by andreycha** [comment]
So the issue was in `DefaultTagProcessorFactory.Load()`: there is no overload of `Activator.CreateInstance()` in .NET Standard which accepts class name. The call was throwing an exception, unable to create tag processors which resulted into an empty document. The call should look like `Activator.CreateInstance(Type.GetType(className))`. Now HTML to PDF conversion works.

I've double checked other calls of `Activator.CreateInstance()`, they look good.

Feel free to include this fix into your PR/republish packages. Thanks for quick response and help!

**Comment by danielgindi** [comment]
@andreycha Fixing, rebasing on 5.5.13.3, and releasing :-)

**Pull request closed without merging**
