### PR TITLE
Fixed bug causing infinite loop in Merging PDFs with incomplete Num Tree

### PR DESCRIPTION
**Pull request by CelerityChip**
Fixes from itextpdf:

https://github.com/itext/itextpdf/commit/5d55de614c87bc72a6e47b0f24e65369d760d1a1

### CODE REVIEW

**Comment by amedee** [comment]
Hi, could you rebase your 2 commits and squash them? Your new commit message can be the same as the description of this pull request. Then force push back to your own repo, and GitHub will automatically update your pull request.

**Comment by CelerityChip** [comment]
Like so?

**Comment by amedee** [comment]
Great!
From your initial comment, I'm guessing that this is a bugfix in the Java version that for some reason apparently didn't get ported to the .NET version, is that correct?

**Comment by CelerityChip** [comment]
Correct.  From the history it looks like the fix has gone through a couple of revisions; this is the latest version of these methods from current source.

**Comment by amedee** [comment]
Good catch. I'll add it to the backlog, to be picked up in the next sprint.

**Comment by blagae** [comment]
This commit was added to itextsharp in June: https://github.com/itext/itextsharp/commit/0d585196a68

Apparently, Github never picked this up because the commit was rebased on top of develop, instead of being merged.

**Pull request closed without merging**
